---
exclude: ^archive/.*|.*/test-data/.*|.*/vendor/.*|.*\.svg$
minimum_pre_commit_version: 2.13.0
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-case-conflict
          - id: mixed-line-ending
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-json
          - id: check-yaml
          - id: check-added-large-files
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            name: Format code (black)
            language_version: python310

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt

    - repo: https://github.com/PyCQA/isort
      rev: 5.9.3
      hooks:
          - id: isort
            args: [-m, '3', -tc]
            name: Format code (isort)
            language_version: python310
            types: [python]

    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args: [--in-place, --remove-all-unused-imports, --remove-unused-variable]
