---
name: Linters/Test pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: System setup
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.5
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Dependencies
              run: poetry install --no-interaction --no-root
            - name: flake8
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  poetry run flake8 . --count  --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                  # black check
                  poetry run black . --check
                  # isort check
                  poetry run isort . --check-only --profile black
            - name: mypy
              run: |
                  poetry run mypy scraper/
    test:
        runs-on: ubuntu-20.04
        needs: lint
        steps:
            - uses: actions/checkout@v2
            - name: System setup
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.5
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Dependencies
              run: |
                  poetry install --no-interaction --no-root
            - name: test
              run: |
                  poetry run pytest -v tests/
