---
name: Linters/Test workflow

on:
    push:
        branches:
            - '!master'
    pull_request:
        branches:
            - '*'
jobs:
    lint-test:
        uses: ./.github/workflows/common-ci.yml
